# Site settings
title: 书豪 的 Blog
SEOTitle: 戚书豪的博客 | GOOD BOY Blog
header-img: img/post-bg-YesOrNo.jpg
email: 919112734@qq.com
description: "二营长，开炮！."
keyword: "BY, BY Blog, 戚书豪的博客,Apple, iPhone"
url: "http://qiletian666.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "天若有情天亦老，人间正道是沧桑!"
sidebar-avatar: /img/about-BY-myphoto.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     qi-shu-hao-15
github_username:    qiletian666
#facebook_username:  baiying.qiu.7
jianshu_username:   8292b078b083
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "百度",
        href: "http://www.baidu.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
